"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Repository root (BASE_DIR is vfoot-backend/src, so two levels up).
REPO_ROOT = BASE_DIR.parent.parent

# Machine-specific configuration lives in a .env that is NEVER committed; see
# .env.example for the full list. This is what lets the same code run unchanged
# on a laptop (SQLite) and on the server (MySQL), which is the whole point.
load_dotenv(REPO_ROOT / ".env")


def _env_bool(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name: str, default: str = "") -> list[str]:
    return [x.strip() for x in os.environ.get(name, default).split(",") if x.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Never hardcoded: set DJANGO_SECRET_KEY in .env. The insecure fallback exists only
# so a fresh clone runs in DEBUG; production refuses to start without a real one
# (see the guard below).
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-dev-only-key")

DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver")

if not DEBUG and SECRET_KEY == "django-insecure-dev-only-key":
    raise RuntimeError(
        "DJANGO_SECRET_KEY must be set when DEBUG is off — refusing to start with "
        "the development fallback key.")


# Application definition

INSTALLED_APPS = [
    # Channels must come before staticfiles so its runserver command takes over
    # (dev), and is what serves the auction WebSocket in production under uvicorn.
    "daphne",
    "channels",
    # Django
    "realdata",
    "vfoot",
    "players",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",

]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# In production the SPA is served from the same origin as the API, so this list is
# typically empty there; in development it points at the Vite dev server.
CORS_ALLOWED_ORIGINS = _env_list(
    "DJANGO_CORS_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Channel layer for the live auction WebSocket. Production points at the Redis that
# already runs on the box (set REDIS_URL, e.g. redis://127.0.0.1:6379/1); with no
# REDIS_URL we use the in-memory layer, which is correct for a single-process dev
# server and for the test-suite (no external dependency), but does NOT fan out
# across multiple worker processes — so production MUST set REDIS_URL.
_REDIS_URL = os.environ.get("REDIS_URL", "").strip()
if _REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [_REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DB_ENGINE: sqlite (default, laptop) | mysql | postgresql. Everything else comes
# from the environment, so moving engine is configuration, never a code change.
_DB_ENGINE = os.environ.get("DB_ENGINE", "sqlite").strip().lower()

if _DB_ENGINE == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.environ.get("DB_NAME", str(BASE_DIR / "db.sqlite3")),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": f"django.db.backends.{_DB_ENGINE}",
            "NAME": os.environ.get("DB_NAME", "vfoot"),
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", ""),
            # utf8mb4 + strict mode: without this MySQL silently truncates rather
            # than raising, which would corrupt player names and feature values.
            **({"OPTIONS": {"charset": "utf8mb4",
                            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'"}}
               if _DB_ENGINE == "mysql" else {}),
        }
    }

# Behind a TLS-terminating reverse proxy, Django must be told the original scheme,
# otherwise it believes every request is plain HTTP and secure cookies never stick.
# All of this is enabled only when DJANGO_SECURE=true (production), so local HTTP
# development is unaffected.
_SECURE = _env_bool("DJANGO_SECURE", not DEBUG)
if _SECURE:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # nginx already redirects http->https; this makes Django refuse to be served
    # over plain HTTP even if the proxy config were changed by mistake.
    SECURE_SSL_REDIRECT = _env_bool("DJANGO_SSL_REDIRECT", True)
    # Start HSTS short: a long max-age is hard to undo if TLS ever breaks.
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    CSRF_TRUSTED_ORIGINS = [
        f"https://{h}" for h in ALLOWED_HOSTS if h not in {"localhost", "127.0.0.1"}
    ]

# How often a LIVE match may be re-scraped, in minutes. The scheduler tick can run
# every minute, but each match is polled at most this often — this is the knob that
# adapts scraping intensity to the machine (a small VPS driving a headless browser
# cannot sustain a per-minute poll across ten simultaneous matches). Override with
# the VFOOT_LIVE_POLL_MINUTES env var; no code change needed to retune it.
VFOOT_LIVE_POLL_MINUTES = float(os.environ.get("VFOOT_LIVE_POLL_MINUTES", "2"))

# Where the scraped/reference datasets live (historical-data/, data_fantacalcio/).
# Auxiliary commands derive their defaults from here instead of hardcoding a path,
# so they run on any machine.
VFOOT_DATA_DIR = Path(os.environ.get("VFOOT_DATA_DIR", str(REPO_ROOT)))
VFOOT_SOFASCORE_CACHE = str(VFOOT_DATA_DIR / "historical-data" / "serie-a"
                            / "sofascore" / "cache")

# Percorso del browser per lo scraping. Sul server usiamo il Chromium di SISTEMA
# (pacchettizzato da Debian) invece di far scaricare a Playwright una copia
# separata: stessa funzione, ~150 MB e un aggiornamento in meno da gestire.
VFOOT_CHROMIUM_PATH = os.environ.get("VFOOT_CHROMIUM_PATH", "") or None

# File-based so expensive season aggregates (voto-puro reference, player values)
# SURVIVE a restart and are shared across worker processes — the default locmem
# cache is per-process and would recompute on every boot. Entries are keyed by a
# data version (match count + last data check), so new results invalidate them.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        # Keep this OUT of the checkout in production: a cache written inside the
        # repo ends up owned by whoever last ran a management command, and the
        # service user then cannot read it.
        'LOCATION': os.environ.get("DJANGO_CACHE_DIR", str(BASE_DIR / '.django_cache')),
        'TIMEOUT': None,
        'OPTIONS': {'MAX_ENTRIES': 500},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# The app is Italian-facing: this makes Django/DRF emit their built-in validation
# messages already translated ("This field is required." -> "Campo obbligatorio."),
# so the frontend can show them to the user as they are.
LANGUAGE_CODE = 'it'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic raccoglie qui i file dell'admin; in produzione li serve nginx,
# perche' Django non deve occuparsi di file statici.
STATIC_ROOT = Path(os.environ.get("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Email + Google sign-in ----------------------------------------------
# Outbound port 25 is blocked on the VPS, so production sends through a relay on
# 587 (STARTTLS). In development EMAIL_BACKEND defaults to the console one, so
# the confirmation flow is fully testable without any mail account.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend" if not DEBUG
    else "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "15"))
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL",
                                    "Vfoot Boosted <no-reply@vfoot.it>")

# Confirmation links point at the SPA, which then calls the verify endpoint.
VFOOT_FRONTEND_BASE_URL = os.environ.get("VFOOT_FRONTEND_BASE_URL",
                                         "http://localhost:5173")

# Empty means the Google button is simply not offered; the endpoint then refuses
# rather than silently accepting unverifiable tokens.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")

# How long a confirmation link stays valid (Django reuses this for its own
# password-reset tokens; 3 days is long enough to survive a spam folder).
PASSWORD_RESET_TIMEOUT = int(os.environ.get("DJANGO_TOKEN_TIMEOUT", str(60 * 60 * 72)))

# Django only prints request tracebacks when DEBUG is on, so in production a 500
# is otherwise a blank page with nothing in the journal. Send them to stderr,
# which systemd captures — `journalctl -u vfoot` then shows the real error.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "[{asctime}] {levelname} {name}: {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": False},
    },
}
