from django.urls import path

from vfoot.api.league_views import (
    AuctionCloseNominationView,
    AuctionCreateView,
    AuctionNominateNextView,
    AuctionPlaceBidView,
    AuctionStateView,
    CompetitionTemplateCreateView,
    CompetitionListView,
    CompetitionDetailUpdateView,
    CompetitionScheduleView,
    CompetitionSchedulePreviewView,
    CompetitionAddQualificationRuleView,
    CompetitionStageBuildDefaultView,
    CompetitionStageCreateView,
    CompetitionStageDetailUpdateView,
    CompetitionStageAddRuleView,
    CompetitionStageListView,
    CompetitionStageResolveView,
    CompetitionPrizeListCreateView,
    FixtureDetailView,
    LeagueStandingsView,
    LeagueTeamLineupView,
    LeagueTeamLineupSaveView,
    CompetitionPrizeDeleteView,
    CompetitionResolveDependenciesView,
    LeagueDetailView,
    LeagueJoinView,
    LeagueListCreateView,
    LeagueMatchdayConcludeView,
    LeagueMatchdayListView,
    LeagueMatchdaySyncView,
    LeagueFixturesView,
    LeagueChampionshipPlayersView,
    LeagueRealFixturesView,
    LeagueRealMatchDetailView,
    LeagueRosterBulkAssignView,
    LeagueRosterImportCSVView,
    PlayerSearchView,
    MarketToggleView,
    LeagueSettingsUpdateView,
    CompetitionStructureView,
    MemberRoleUpdateView,
    LeagueReferenceSeasonView,
    RealSeasonListView,
    TeamRosterAddView,
    TeamRosterRemoveView,
    TeamRosterView,
)
from vfoot.api.simulation_views import (
    SimulationFixtureDetailView,
    SimulationFixturesView,
    SimulationOverviewView,
)
from vfoot.api.views import (
    LineupContextView,
    LoginView,
    LogoutView,
    MatchDetailView,
    MatchListView,
    MeView,
    RegisterView,
    SaveLineupView,
)

urlpatterns = [
    path("leagues", LeagueListCreateView.as_view(), name="league-list-create"),
    path("leagues/join", LeagueJoinView.as_view(), name="league-join"),
    path("leagues/<int:league_id>", LeagueDetailView.as_view(), name="league-detail"),
    path("leagues/<int:league_id>/fixtures", LeagueFixturesView.as_view(), name="league-fixtures"),
    path("leagues/<int:league_id>/championship-players", LeagueChampionshipPlayersView.as_view(), name="league-championship-players"),
    path("leagues/<int:league_id>/real-fixtures", LeagueRealFixturesView.as_view(), name="league-real-fixtures"),
    path("leagues/<int:league_id>/real-matches/<int:match_id>", LeagueRealMatchDetailView.as_view(), name="league-real-match-detail"),
    path("leagues/<int:league_id>/standings", LeagueStandingsView.as_view(), name="league-standings"),
    path("leagues/<int:league_id>/lineup", LeagueTeamLineupView.as_view(), name="league-team-lineup"),
    path("leagues/<int:league_id>/lineup/save", LeagueTeamLineupSaveView.as_view(), name="league-team-lineup-save"),
    path("fixtures/<int:fixture_id>", FixtureDetailView.as_view(), name="fixture-detail"),
    path("leagues/<int:league_id>/matchdays/sync", LeagueMatchdaySyncView.as_view(), name="league-matchday-sync"),
    path("leagues/<int:league_id>/matchdays", LeagueMatchdayListView.as_view(), name="league-matchday-list"),
    path(
        "leagues/<int:league_id>/matchdays/<int:fantasy_matchday_id>/conclude",
        LeagueMatchdayConcludeView.as_view(),
        name="league-matchday-conclude",
    ),
    path(
        "leagues/<int:league_id>/members/<int:membership_id>/role",
        MemberRoleUpdateView.as_view(),
        name="league-member-role",
    ),
    path("leagues/<int:league_id>/market", MarketToggleView.as_view(), name="league-market-toggle"),
    path("leagues/<int:league_id>/settings", LeagueSettingsUpdateView.as_view(), name="league-settings"),
    path("leagues/<int:league_id>/competitions/<int:competition_id>/structure",
         CompetitionStructureView.as_view(), name="competition-structure"),
    path("leagues/<int:league_id>/reference-season", LeagueReferenceSeasonView.as_view(), name="league-reference-season"),
    path("real-seasons", RealSeasonListView.as_view(), name="real-seasons-list"),
    path("leagues/<int:league_id>/teams/<int:team_id>/roster", TeamRosterView.as_view(), name="team-roster"),
    path("leagues/<int:league_id>/teams/<int:team_id>/roster/add", TeamRosterAddView.as_view(), name="team-roster-add"),
    path(
        "leagues/<int:league_id>/teams/<int:team_id>/roster/remove",
        TeamRosterRemoveView.as_view(),
        name="team-roster-remove",
    ),
    path(
        "leagues/<int:league_id>/roster/bulk-assign",
        LeagueRosterBulkAssignView.as_view(),
        name="league-roster-bulk-assign",
    ),
    path(
        "leagues/<int:league_id>/roster/import-csv",
        LeagueRosterImportCSVView.as_view(),
        name="league-roster-import-csv",
    ),
    path(
        "leagues/<int:league_id>/competitions/template",
        CompetitionTemplateCreateView.as_view(),
        name="competition-template-create",
    ),
    path("leagues/<int:league_id>/competitions", CompetitionListView.as_view(), name="competition-list"),
    path("competitions/<int:competition_id>", CompetitionDetailUpdateView.as_view(), name="competition-detail"),
    path(
        "competitions/<int:competition_id>/schedule/preview",
        CompetitionSchedulePreviewView.as_view(),
        name="competition-schedule-preview",
    ),
    path("competitions/<int:competition_id>/schedule", CompetitionScheduleView.as_view(), name="competition-schedule"),
    path("competitions/<int:competition_id>/stages", CompetitionStageListView.as_view(), name="competition-stage-list"),
    path("competitions/<int:competition_id>/stages/create", CompetitionStageCreateView.as_view(), name="competition-stage-create"),
    path(
        "competitions/<int:competition_id>/stages/default-build",
        CompetitionStageBuildDefaultView.as_view(),
        name="competition-stage-build-default",
    ),
    path("stages/<int:stage_id>/rules", CompetitionStageAddRuleView.as_view(), name="competition-stage-add-rule"),
    path("stages/<int:stage_id>", CompetitionStageDetailUpdateView.as_view(), name="competition-stage-detail"),
    path("stages/<int:stage_id>/resolve", CompetitionStageResolveView.as_view(), name="competition-stage-resolve"),
    path("competitions/<int:competition_id>/prizes", CompetitionPrizeListCreateView.as_view(), name="competition-prize-list-create"),
    path("prizes/<int:prize_id>", CompetitionPrizeDeleteView.as_view(), name="competition-prize-delete"),
    path(
        "competitions/<int:competition_id>/rules",
        CompetitionAddQualificationRuleView.as_view(),
        name="competition-add-rule",
    ),
    path(
        "competitions/<int:competition_id>/resolve",
        CompetitionResolveDependenciesView.as_view(),
        name="competition-resolve-dependencies",
    ),
    path("leagues/<int:league_id>/auctions", AuctionCreateView.as_view(), name="auction-create"),
    path("auctions/<int:auction_id>", AuctionStateView.as_view(), name="auction-state"),
    path("auctions/<int:auction_id>/nominate-next", AuctionNominateNextView.as_view(), name="auction-nominate-next"),
    path("nominations/<int:nomination_id>/bid", AuctionPlaceBidView.as_view(), name="auction-place-bid"),
    path("nominations/<int:nomination_id>/close", AuctionCloseNominationView.as_view(), name="auction-close-nomination"),
    path("players/search", PlayerSearchView.as_view(), name="player-search"),
    path("auth/register", RegisterView.as_view(), name="auth-register"),
    path("auth/login", LoginView.as_view(), name="auth-login"),
    path("auth/me", MeView.as_view(), name="auth-me"),
    path("auth/logout", LogoutView.as_view(), name="auth-logout"),
    path("lineup/context", LineupContextView.as_view(), name="lineup-context"),
    path("lineup/save", SaveLineupView.as_view(), name="lineup-save"),
    path("matches", MatchListView.as_view(), name="matches-list"),
    path("matches/<str:match_id>", MatchDetailView.as_view(), name="match-detail"),
    path(
        "simulations/historical-vfoot/latest",
        SimulationOverviewView.as_view(),
        name="simulation-overview",
    ),
    path(
        "simulations/historical-vfoot/latest/fixtures",
        SimulationFixturesView.as_view(),
        name="simulation-fixtures",
    ),
    path(
        "simulations/historical-vfoot/latest/fixtures/<int:fixture_id>",
        SimulationFixtureDetailView.as_view(),
        name="simulation-fixture-detail",
    ),
]
