# Generated by Django 5.2.10 on 2026-01-29 00:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('grid', 'Grid'), ('polygons', 'Polygons')], default='grid', max_length=20)),
                ('name', models.CharField(default='Default grid', max_length=80)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HeatmapGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_w', models.IntegerField(default=30)),
                ('grid_h', models.IntegerField(default=20)),
                ('values', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appearance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap', to='realdata.matchappearance')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('x0', models.FloatField()),
                ('y0', models.FloatField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('col', models.IntegerField(blank=True, null=True)),
                ('zone_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='vfoot.zoneset')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerZonePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.FloatField()),
                ('activity_score', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_presences', to='realdata.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_presences', to='realdata.player')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_presences', to='vfoot.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'zone'], name='vfoot_playe_match_i_4239ac_idx')],
                'unique_together': {('match', 'player', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='ZoneDuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.FloatField(default=0.0)),
                ('away_score', models.FloatField(default=0.0)),
                ('winner', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('draw', 'Draw')], default='draw', max_length=10)),
                ('intensity', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_duels', to='realdata.match')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='vfoot.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['match'], name='vfoot_zoned_match_i_cfb187_idx')],
                'unique_together': {('match', 'zone')},
            },
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['zone_set', 'code'], name='vfoot_zone_zone_se_c2a526_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('zone_set', 'code')},
        ),
    ]
