# Generated by Django 5.2.10 on 2026-02-12 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLineupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=64)),
                ('matchday_id', models.CharField(max_length=64)),
                ('lineup_id', models.CharField(max_length=64)),
                ('gk_player_id', models.CharField(blank=True, max_length=64, null=True)),
                ('starter_player_ids', models.JSONField(default=list)),
                ('bench_player_ids', models.JSONField(default=list)),
                ('starter_backups', models.JSONField(default=list)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['league_id', 'matchday_id'], name='vfoot_saved_league__c99ccd_idx')],
                'unique_together': {('league_id', 'matchday_id')},
            },
        ),
    ]
