# Generated by Django 5.2.10 on 2026-02-12 10:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0001_initial'),
        ('vfoot', '0002_savedlineupsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('competition_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout')], default='round_robin', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('done', 'Done')], default='draft', max_length=16)),
                ('points_win', models.IntegerField(default=3)),
                ('points_draw', models.IntegerField(default=1)),
                ('points_loss', models.IntegerField(default=0)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionQualificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_stage', models.CharField(choices=[('halfway', 'Halfway'), ('final', 'Final')], default='final', max_length=12)),
                ('mode', models.CharField(choices=[('table_range', 'Table Range'), ('winner', 'Winner')], default='table_range', max_length=16)),
                ('rank_from', models.IntegerField(blank=True, null=True)),
                ('rank_to', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_rules', to='vfoot.fantasycompetition')),
                ('source_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by_rules', to='vfoot.fantasycompetition')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_fantasy_leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fantasycompetition',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='vfoot.fantasyleague'),
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='vfoot.fantasyleague')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField(default=1)),
                ('leg_no', models.IntegerField(default=1)),
                ('kickoff', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=16)),
                ('home_total', models.FloatField(default=0.0)),
                ('away_total', models.FloatField(default=0.0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='vfoot.fantasycompetition')),
                ('source_real_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_fantasy_fixtures', to='realdata.match')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_fixtures', to='vfoot.fantasyteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_fixtures', to='vfoot.fantasyteam')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Rule')], default='manual', max_length=12)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='vfoot.fantasycompetition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='vfoot.fantasyteam')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager')], default='manager', max_length=16)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='vfoot.fantasyleague')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='team', to='vfoot.leaguemembership'),
        ),
        migrations.AlterUniqueTogether(
            name='fantasycompetition',
            unique_together={('league', 'name')},
        ),
        migrations.CreateModel(
            name='FantasyRosterSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_price', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fantasy_rosters', to='realdata.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_slots', to='vfoot.fantasyteam')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'released_at'], name='vfoot_fanta_team_id_914fa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='FantasyLineupSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_player_ids', models.JSONField(default=list)),
                ('bench_player_ids', models.JSONField(default=list)),
                ('starter_backups', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_submissions', to='vfoot.fantasyfixture')),
                ('gk_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_gk_submissions', to='realdata.player')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_lineups', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_submissions', to='vfoot.fantasyteam')),
            ],
            options={
                'indexes': [models.Index(fields=['fixture', 'team'], name='vfoot_fanta_fixture_3cba57_idx')],
                'unique_together': {('fixture', 'team')},
            },
        ),
        migrations.AddIndex(
            model_name='fantasyfixture',
            index=models.Index(fields=['competition', 'round_no'], name='vfoot_fanta_competi_8b580d_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasyfixture',
            index=models.Index(fields=['status'], name='vfoot_fanta_status_55fed1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fantasyfixture',
            unique_together={('competition', 'round_no', 'leg_no', 'home_team', 'away_team')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together={('competition', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='leaguemembership',
            unique_together={('league', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='fantasyteam',
            unique_together={('league', 'name')},
        ),
    ]
