# Generated by Django 5.2.10 on 2026-02-12 11:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0001_initial'),
        ('vfoot', '0003_fantasycompetition_competitionqualificationrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='market_open',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AuctionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Auction', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('nomination_order', models.JSONField(default=list)),
                ('nomination_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_auctions', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_sessions', to='vfoot.fantasyleague')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_nominations', to='vfoot.fantasyteam')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='vfoot.leaguemembership')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_nominations', to='realdata.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='vfoot.auctionsession')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_bids', to='vfoot.leaguemembership')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='vfoot.auctionnomination')),
            ],
            options={
                'indexes': [models.Index(fields=['nomination', 'amount'], name='vfoot_aucti_nominat_4e7467_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auctionnomination',
            index=models.Index(fields=['session', 'status'], name='vfoot_aucti_session_dc722d_idx'),
        ),
    ]
