# Generated by Django 5.2.10 on 2026-02-12 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0004_fantasyleague_invite_code_fantasyleague_market_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionqualificationrule',
            name='mode',
            field=models.CharField(choices=[('table_range', 'Table Range'), ('winner', 'Winner'), ('loser', 'Loser')], default='table_range', max_length=16),
        ),
        migrations.CreateModel(
            name='CompetitionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('stage_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout')], default='round_robin', max_length=24)),
                ('order_index', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('done', 'Done')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='vfoot.fantasycompetition')),
            ],
            options={
                'ordering': ['order_index', 'id'],
                'unique_together': {('competition', 'name')},
            },
        ),
        migrations.AddField(
            model_name='fantasyfixture',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='vfoot.competitionstage'),
        ),
        migrations.CreateModel(
            name='CompetitionStageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('table_range', 'Table Range'), ('winners', 'Winners'), ('losers', 'Losers')], default='winners', max_length=16)),
                ('rank_from', models.IntegerField(blank=True, null=True)),
                ('rank_to', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_out', to='vfoot.competitionstage')),
                ('target_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_in', to='vfoot.competitionstage')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionStageParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Rule')], default='manual', max_length=12)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='vfoot.competitionstage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_entries', to='vfoot.fantasyteam')),
            ],
            options={
                'unique_together': {('stage', 'team')},
            },
        ),
    ]
