# Generated by Django 5.2.10 on 2026-02-12 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0001_initial'),
        ('vfoot', '0005_alter_competitionqualificationrule_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyMatchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_matchday', models.IntegerField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('concluded', 'Concluded')], default='planned', max_length=16)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('concluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concluded_fantasy_matchdays', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_matchdays', to='vfoot.fantasyleague')),
                ('real_competition_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fantasy_matchdays', to='realdata.competitionseason')),
            ],
            options={
                'ordering': ['real_matchday', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fantasyfixture',
            name='fantasy_matchday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='vfoot.fantasymatchday'),
        ),
        migrations.AddIndex(
            model_name='fantasymatchday',
            index=models.Index(fields=['league', 'status'], name='vfoot_fanta_league__78c5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasymatchday',
            index=models.Index(fields=['real_competition_season', 'real_matchday'], name='vfoot_fanta_real_co_4d40d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fantasymatchday',
            unique_together={('league', 'real_competition_season', 'real_matchday')},
        ),
    ]
