# Generated by Django 5.2.10 on 2026-02-12 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0006_fantasymatchday_fantasyfixture_fantasy_matchday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('condition_type', models.CharField(choices=[('final_table_range', 'Final table range'), ('stage_table_range', 'Stage table range'), ('stage_winner', 'Stage winner'), ('stage_loser', 'Stage loser')], default='final_table_range', max_length=24)),
                ('rank_from', models.IntegerField(blank=True, null=True)),
                ('rank_to', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='vfoot.fantasycompetition')),
                ('source_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awarded_prizes', to='vfoot.competitionstage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
