# Generated by Django 5.2.10 on 2026-06-08 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0007_competitionprize'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyFixtureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vfoot_home', models.FloatField(default=0.0)),
                ('vfoot_away', models.FloatField(default=0.0)),
                ('payload', models.JSONField(default=dict)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='vfoot.fantasyfixture')),
            ],
        ),
    ]
