# Generated by Django 5.2.10 on 2026-06-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0008_fantasyfixturedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionqualificationrule',
            name='source_round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
