# Generated by Django 5.2.10 on 2026-06-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0009_competitionqualificationrule_source_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionstage',
            name='double_round',
            field=models.BooleanField(default=False),
        ),
    ]
