# Generated by Django 5.2.10 on 2026-06-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0005_playeronpitchinterval'),
        ('vfoot', '0010_competitionstage_double_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasycompetition',
            name='end_matchday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fantasycompetition',
            name='start_matchday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='reference_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fantasy_leagues', to='realdata.competitionseason'),
        ),
    ]
