# Generated by Django 5.2.10 on 2026-06-16 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0006_match_data_checked_at_match_data_ready_match_status_and_more'),
        ('vfoot', '0011_fantasycompetition_end_matchday_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('neutral_mean', "Neutral mean (6 d'ufficio)")], default='neutral_mean', max_length=24)),
                ('outfield_scale', models.FloatField(default=1.0)),
                ('gk_goals_prevented', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_office_overrides', to=settings.AUTH_USER_MODEL)),
                ('fantasy_matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_overrides', to='vfoot.fantasymatchday')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_overrides', to='vfoot.fantasyleague')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_overrides', to='realdata.match')),
            ],
            options={
                'indexes': [models.Index(fields=['league', 'fantasy_matchday'], name='vfoot_offic_league__8affd7_idx'), models.Index(fields=['match', 'is_active'], name='vfoot_offic_match_i_b79c21_idx')],
                'unique_together': {('league', 'match')},
            },
        ),
    ]
