# Generated by Django 5.2.10 on 2026-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0012_officeoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='mode',
            field=models.CharField(choices=[('aura', 'Aura'), ('classic', 'Classic')], default='aura', max_length=16),
        ),
    ]
