# Generated by Django 5.2.10 on 2026-06-16 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0007_player_classic_role_player_role_source'),
        ('vfoot', '0013_fantasyleague_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguePlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('POR', 'Portiere'), ('DIF', 'Difensore'), ('CEN', 'Centrocampista'), ('ATT', 'Attaccante')], max_length=3)),
                ('source', models.CharField(choices=[('seed', 'Seed (TM)'), ('admin', 'Admin override')], default='seed', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_roles', to='vfoot.fantasyleague')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_roles', to='realdata.player')),
            ],
            options={
                'indexes': [models.Index(fields=['league', 'role'], name='vfoot_leagu_league__3ebd45_idx')],
                'unique_together': {('league', 'player')},
            },
        ),
    ]
