# Generated by Django 5.2.10 on 2026-06-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0014_leagueplayerrole'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedlineupsnapshot',
            unique_together={('league_id', 'matchday_id', 'lineup_id')},
        ),
    ]
