# Generated by Django 5.2.10 on 2026-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0015_alter_savedlineupsnapshot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='max_substitutions',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
