# Generated by Django 5.2.10 on 2026-06-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0016_fantasyleague_max_substitutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='defense_bonus_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='defense_bonus_mode',
            field=models.CharField(choices=[('add_own', 'Aggiunto alla propria squadra'), ('subtract_opponent', 'Sottratto alla squadra avversaria')], default='add_own', max_length=20),
        ),
    ]
