# Generated by Django 5.2.10 on 2026-07-22 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0012_playerteamstint_tm_position'),
        ('vfoot', '0018_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='role_mode',
            field=models.CharField(choices=[('mitigated', "Mitigata (priorita' Transfermarkt)"), ('data', 'Pura dai dati')], default='mitigated', max_length=10),
        ),
        migrations.CreateModel(
            name='SeasonPlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('role_data', models.CharField(blank=True, default='', max_length=3)),
                ('role_mitigated', models.CharField(blank=True, default='', max_length=3)),
                ('method', models.CharField(choices=[('category', 'Categoria misurata'), ('tm', 'Posizione TM'), ('default', 'Default posizionale'), ('unknown', 'Ignoto')], default='unknown', max_length=10)),
                ('tm_position', models.CharField(blank=True, default='', max_length=40)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_roles', to='realdata.competitionseason')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_roles', to='realdata.player')),
            ],
            options={
                'indexes': [models.Index(fields=['competition_season', 'method'], name='vfoot_seaso_competi_05a428_idx')],
                'unique_together': {('competition_season', 'player')},
            },
        ),
    ]
