# Generated by Django 5.2.10 on 2026-07-22 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0012_playerteamstint_tm_position'),
        ('vfoot', '0019_season_player_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('player_role', 'Ruolo di un giocatore'), ('other', 'Altro')], default='player_role', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('question', models.TextField(blank=True, default='')),
                ('options', models.JSONField(default=list)),
                ('proposed', models.CharField(blank=True, default='', max_length=32)),
                ('rationale', models.TextField(blank=True, default='')),
                ('blocks_market', models.BooleanField(default=False)),
                ('consultation_open', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Aperta'), ('resolved', 'Risolta'), ('cancelled', 'Annullata')], default='open', max_length=10)),
                ('outcome', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='vfoot.fantasyleague')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_decisions', to='realdata.player')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueDecisionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vfoot.leaguedecision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='leaguedecision',
            index=models.Index(fields=['league', 'status'], name='vfoot_leagu_league__1f7ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='leaguedecision',
            index=models.Index(fields=['league', 'blocks_market', 'status'], name='vfoot_leagu_league__1b6cd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaguedecision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('league', 'kind', 'player'), name='uniq_open_decision_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='leaguedecisionvote',
            constraint=models.UniqueConstraint(fields=('decision', 'user'), name='uniq_vote_per_user'),
        ),
    ]
