# Generated by Django 5.2.10 on 2026-07-23 16:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0020_league_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctionnomination',
            name='call_mode',
            field=models.CharField(choices=[('manual', 'Manuale'), ('random', 'Casuale'), ('random_role', 'Casuale per ruolo'), ('assign', 'Assegnazione diretta')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='auctionnomination',
            name='roster_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_nomination', to='vfoot.fantasyrosterslot'),
        ),
        migrations.AddField(
            model_name='auctionnomination',
            name='winning_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='initial_budget',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='slots_def',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='slots_fwd',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='slots_gk',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='slots_mid',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='auctionnomination',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=16),
        ),
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_events', to=settings.AUTH_USER_MODEL)),
                ('nomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='vfoot.auctionnomination')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vfoot.auctionsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='vfoot_aucti_session_7050d9_idx')],
            },
        ),
    ]
