# Generated by Django 5.2.10 on 2026-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0021_auctionbid_is_void_auctionnomination_call_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonplayerrole',
            name='method',
            field=models.CharField(choices=[('category', 'Categoria misurata'), ('tm', 'Posizione TM'), ('sofa', 'Posizione SofaScore'), ('default', 'Default posizionale'), ('unknown', 'Ignoto')], default='unknown', max_length=10),
        ),
    ]
