# Generated by Django 5.2.10 on 2026-07-24 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0017_alter_player_classic_role_seed'),
        ('vfoot', '0022_alter_seasonplayerrole_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('role_data', models.CharField(blank=True, default='', max_length=3)),
                ('role_mitigated', models.CharField(blank=True, default='', max_length=3)),
                ('method', models.CharField(choices=[('category', 'Categoria misurata'), ('tm', 'Posizione TM'), ('sofa', 'Posizione SofaScore'), ('default', 'Default posizionale'), ('unknown', 'Ignoto')], default='unknown', max_length=10)),
                ('tm_position', models.CharField(blank=True, default='', max_length=40)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_role', to='realdata.player')),
            ],
        ),
        migrations.DeleteModel(
            name='SeasonPlayerRole',
        ),
        migrations.AddIndex(
            model_name='currentplayerrole',
            index=models.Index(fields=['method'], name='vfoot_curre_method_09669c_idx'),
        ),
    ]
