# Generated by Django 5.2.10 on 2026-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0024_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='keeper_clean_sheet_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fantasymatchday',
            name='ruleset_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
