# Generated by Django 5.2.10 on 2026-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0025_fantasyleague_keeper_clean_sheet_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='enforce_lineup_deadline',
            field=models.BooleanField(default=True),
        ),
    ]
