# Generated by Django 5.2.10 on 2026-07-28 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0019_matchshot_situation'),
        ('vfoot', '0026_fantasyleague_enforce_lineup_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mercato di riparazione', max_length=120)),
                ('status', models.CharField(choices=[('open', 'Aperta'), ('suspended', 'Sospesa'), ('closed', 'Chiusa')], default='open', max_length=16)),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('credit_recovery_mode', models.CharField(choices=[('fixed', 'Credito fisso'), ('frac30', "30% del prezzo d'acquisto"), ('frac50', "50% del prezzo d'acquisto"), ('frac75', "75% del prezzo d'acquisto")], default='fixed', max_length=10)),
                ('fixed_recovery_amount', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_market_sessions', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_sessions', to='vfoot.fantasyleague')),
            ],
        ),
        migrations.CreateModel(
            name='MarketOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('recovery_amount', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('leading', 'In testa'), ('outbid', 'Superata'), ('accepted', 'Accettata'), ('settled', 'Conclusa'), ('rejected', 'Rifiutata'), ('cancelled', 'Annullata')], default='leading', max_length=16)),
                ('deadline_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acquire_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_market_offer', to='vfoot.fantasyrosterslot')),
                ('release_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_offers_out', to='realdata.player')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_market_offers', to=settings.AUTH_USER_MODEL)),
                ('target_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_offers_in', to='realdata.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_offers', to='vfoot.fantasyteam')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='vfoot.marketsession')),
            ],
        ),
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_events', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='vfoot.marketoffer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vfoot.marketsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='marketsession',
            index=models.Index(fields=['league', 'status'], name='vfoot_marke_league__65345b_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'suspended'])), fields=('league',), name='uniq_live_market_session_per_league'),
        ),
        migrations.AddIndex(
            model_name='marketoffer',
            index=models.Index(fields=['session', 'status'], name='vfoot_marke_session_8d1f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketoffer',
            index=models.Index(fields=['session', 'target_player', 'status'], name='vfoot_marke_session_549b80_idx'),
        ),
        migrations.AddIndex(
            model_name='marketoffer',
            index=models.Index(fields=['team', 'status'], name='vfoot_marke_team_id_7eca4b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketevent',
            index=models.Index(fields=['session', 'created_at'], name='vfoot_marke_session_040c0b_idx'),
        ),
    ]
