# Generated by Django 5.2.10 on 2026-07-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0027_marketsession_marketoffer_marketevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentplayerrole',
            name='role_margin',
            field=models.FloatField(default=1.0),
        ),
    ]
