# Generated by Django 5.2.10 on 2026-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0029_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='crest',
            field=models.TextField(blank=True, default=''),
        ),
    ]
