# Generated by Django 5.2.10 on 2026-07-31 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0031_competition_format_stage_legs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionprize',
            name='source_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awarded_prizes', to='vfoot.competitionstage'),
        ),
    ]
