# Generated by Django 5.2.10 on 2026-08-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0032_prize_stage_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasymatchday',
            name='awaiting_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fantasymatchday',
            name='awaiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fantasymatchday',
            name='nudged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fantasymatchday',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('awaiting', 'Awaiting'), ('concluded', 'Concluded')], default='planned', max_length=16),
        ),
    ]
