# Generated by Django 5.2.10 on 2026-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0033_fantasymatchday_awaiting_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeoverride',
            name='gk_goals_prevented',
        ),
        migrations.RemoveField(
            model_name='officeoverride',
            name='outfield_scale',
        ),
        migrations.RemoveField(
            model_name='officeoverride',
            name='template',
        ),
        migrations.AddField(
            model_name='officeoverride',
            name='voto',
            field=models.FloatField(default=6.0),
        ),
    ]
