# Generated by Django 5.2.10 on 2026-08-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0034_remove_officeoverride_gk_goals_prevented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionprize',
            name='stat',
            field=models.CharField(blank=True, choices=[('avg_score', 'Media punteggio'), ('goals_for', 'Gol fatti'), ('goals_against', 'Gol subiti'), ('best_round', 'Miglior punteggio in una giornata'), ('wins', 'Vittorie')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='competitionprize',
            name='condition_type',
            field=models.CharField(choices=[('final_table_range', 'Final table range'), ('stage_table_range', 'Stage table range'), ('stage_winner', 'Stage winner'), ('stage_loser', 'Stage loser'), ('stat_top', 'Highest of a measure'), ('stat_bottom', 'Lowest of a measure')], default='final_table_range', max_length=24),
        ),
    ]
