# Generated by Django 5.2.10 on 2026-08-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0035_competitionprize_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyfixture',
            name='home_advantage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='home_advantage_bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
