# Generated by Django 5.2.10 on 2026-08-06 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0036_fantasyfixture_home_advantage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasycompetition',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AwardedPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded', to='vfoot.competitionprize')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honours', to='vfoot.fantasyteam')),
            ],
            options={
                'indexes': [models.Index(fields=['team'], name='vfoot_award_team_id_a394fe_idx')],
                'unique_together': {('prize', 'team')},
            },
        ),
    ]
