# Generated by Django 5.2.10 on 2026-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0037_fantasycompetition_completed_at_awardedprize'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyfixture',
            name='shootout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
