# Generated by Django 5.2.10 on 2026-08-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0038_fantasyfixture_shootout'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='lineup_lock_mode',
            field=models.CharField(choices=[('matchday', "Al primo calcio d'inizio della giornata"), ('player', "Ogni giocatore all'inizio della sua partita")], default='matchday', max_length=10),
        ),
    ]
