# Generated by Django 5.2.10 on 2026-08-07 13:56

from django.db import migrations, models


def freeze_current_identities(apps, schema_editor):
    """Congela nome e stemma delle squadre sui premi gia' assegnati.

    Copia la squadra COM'E' ADESSO, che e' esattamente quello che l'albo d'oro
    mostrava prima di questi campi: non recupera un'identita' perduta (non c'e'
    da nessuna parte), ma smette di perderne altre da qui in avanti.
    """
    AwardedPrize = apps.get_model('vfoot', 'AwardedPrize')
    rows = []
    for a in AwardedPrize.objects.select_related('team'):
        a.team_name = a.team.name
        a.team_crest = a.team.crest
        rows.append(a)
    if rows:
        AwardedPrize.objects.bulk_update(rows, ['team_name', 'team_crest'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0039_fantasyleague_lineup_lock_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardedprize',
            name='team_crest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='awardedprize',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        # Le righe gia' scritte prenderebbero comunque la strada del fallback; il
        # riempimento serve a non lasciarne nemmeno una che dipenda dal futuro.
        migrations.RunPython(freeze_current_identities, migrations.RunPython.noop),
    ]
