# Generated by Django 5.2.10 on 2026-08-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0040_awardedprize_team_crest_awardedprize_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentplayerrole',
            name='role_boundary',
            field=models.FloatField(default=0.0),
        ),
    ]
