# Generated by Django 5.2.10 on 2026-08-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0041_currentplayerrole_role_boundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyleague',
            name='market_open',
        ),
    ]
