# Generated by Django 5.2.10 on 2026-08-10 23:24

from django.db import migrations, models


def backfill_full_recovery(apps, schema_editor):
    """I contratti gia' chiusi valevano, di fatto, recupero completo.

    Il budget si e' sempre calcolato dai soli contratti aperti: chiudere uno slot
    ne toglieva il prezzo dalla spesa, cioe' restituiva tutto. Scriverlo qui a
    chiare lettere e' quello che tiene FERMI i saldi di ogni lega esistente: la
    formula nuova sottrae (prezzo - incasso), e con incasso = prezzo quella
    differenza e' zero. Senza il backfill (incasso NULL letto come 0) ogni
    svincolo del passato diventerebbe di colpo una perdita secca.
    """
    Slot = apps.get_model("vfoot", "FantasyRosterSlot")
    Slot.objects.filter(released_at__isnull=False, sale_price__isnull=True).update(
        sale_price=models.F("purchase_price"))


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0042_remove_fantasyleague_market_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyrosterslot',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_full_recovery, migrations.RunPython.noop),
    ]
