# Generated by Django 5.2.10 on 2026-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0043_roster_slot_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionnomination',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('unsold', 'Invenduto')], default='open', max_length=16),
        ),
    ]
