# Generated by Django 5.2.10 on 2026-08-14 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0044_alter_auctionnomination_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Non funziona'), ('idea', 'Proposta'), ('altro', 'Altro')], default='altro', max_length=10)),
                ('message', models.TextField()),
                ('page', models.CharField(blank=True, default='', max_length=200)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('viewport', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Da leggere'), ('seen', 'Letta'), ('done', 'Chiusa')], default='new', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='vfoot_feedb_status_414951_idx'), models.Index(fields=['-created_at'], name='vfoot_feedb_created_ad5289_idx')],
            },
        ),
    ]
