# Generated by Django 5.2.10 on 2026-08-17 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _bytea_senza_compressione(apps, schema_editor):
    """Su PostgreSQL: dire a TOAST di non provare a comprimere i byte.

    Una bytea oltre i 2 KB finisce comunque fuori riga, ma per default Postgres
    tenta prima di comprimerla. Dentro c'è un WebP, cioè roba già compressa: il
    tentativo non guadagna niente e si paga in CPU a ogni scrittura. EXTERNAL
    tiene il fuori-riga e salta la compressione.

    Su SQLite (lo sviluppo) non esiste niente di tutto questo, e la migrazione
    non fa nulla.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE vfoot_crestimage ALTER COLUMN data SET STORAGE EXTERNAL")


def _bytea_compressione_default(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE vfoot_crestimage ALTER COLUMN data SET STORAGE EXTENDED")


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0046_case_insensitive_login_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrestImage',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.BinaryField(blank=True, default=b'')),
                ('content_type', models.CharField(default='image/webp', max_length=32)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=200)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crest_revocations', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crest_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vfoot.crestimage')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crest_reports', to='vfoot.fantasyleague')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crest_reports', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crest_reports', to='vfoot.fantasyteam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crestimage',
            index=models.Index(fields=['-created_at'], name='vfoot_crest_created_6f9938_idx'),
        ),
        migrations.AddConstraint(
            model_name='crestreport',
            constraint=models.UniqueConstraint(fields=('image', 'league', 'reporter'), name='uniq_crest_report_per_reporter'),
        ),
        migrations.RunPython(_bytea_senza_compressione, _bytea_compressione_default),
    ]
