# Generated by Django 5.2.10 on 2026-08-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0049_decision_digest_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='defense_bonus_gate',
            field=models.CharField(choices=[('starters', "Formazione schierata (4 difensori dal 1')"), ('effective', 'Formazione acquisita (4 difensori con voto)')], default='starters', max_length=10),
        ),
    ]
