# Generated by Django 5.2.10 on 2026-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0050_fantasyleague_defense_bonus_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='sv_office_vote',
            field=models.FloatField(default=0.0),
        ),
    ]
