# Generated by Django 5.2.10 on 2026-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0025_player_short_name_source'),
        ('vfoot', '0051_fantasyleague_sv_office_vote'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='auctionnomination',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('session',), name='uniq_open_nomination_per_session'),
        ),
    ]
