# Generated by Django 5.2.10 on 2026-08-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0057_remove_savedlineupsnapshot_edited_after_kickoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsession',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
