# Generated by Django 5.2.10 on 2026-08-25 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0059_market_sessions_already_opened'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trades', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_trades', to='vfoot.fantasyleague')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_a', to='vfoot.fantasyteam')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_b', to='vfoot.fantasyteam')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('batch', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_budgets', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_grants', to='vfoot.fantasyteam')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_legs', to='vfoot.playertrade')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='playertrade',
            index=models.Index(fields=['league', 'created_at'], name='vfoot_playe_league__d42cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetgrant',
            index=models.Index(fields=['team', 'created_at'], name='vfoot_budge_team_id_c779b6_idx'),
        ),
    ]
