# Generated by Django 5.2.10 on 2026-08-25 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0060_player_trade_and_budget_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyrosterslot',
            name='from_trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='vfoot.playertrade'),
        ),
    ]
