# Generated by Django 5.2.10 on 2026-08-28 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0061_roster_slot_from_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='news_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('body', models.CharField(blank=True, default='', max_length=280)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'product news',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['active', 'published_at'], name='vfoot_produ_active_6ceafc_idx')],
            },
        ),
    ]
