# Generated by Django 5.2.10 on 2026-08-31 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0029_matchshot_assist_player'),
        ('vfoot', '0062_userprofile_news_seen_at_productnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEventNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('goal', 'gol'), ('red', 'espulsione')], max_length=8)),
                ('occurrence', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retracted_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_notices', to='realdata.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_notices', to='realdata.player')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['match', 'kind'], name='vfoot_livee_match_i_326cef_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'player', 'kind', 'occurrence'), name='uniq_live_notice_per_event')],
            },
        ),
    ]
