# Generated by Django 5.2.10 on 2026-09-19 08:46

import vfoot.models.lineup
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfoot', '0064_seed_live_event_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlineupsnapshot',
            name='bench_player_ids',
            field=vfoot.models.lineup.PlayerIdListField(default=list),
        ),
        migrations.AlterField(
            model_name='savedlineupsnapshot',
            name='starter_player_ids',
            field=vfoot.models.lineup.PlayerIdListField(default=list),
        ),
    ]
