# Generated by Django 5.2.10 on 2026-01-29 00:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('country', models.CharField(blank=True, default='', max_length=40)),
                ('external_source', models.CharField(blank=True, default='', max_length=50)),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['external_source', 'external_id'], name='realdata_co_externa_661441_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('num_rounds', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='realdata.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='realdata.season')),
            ],
            options={
                'unique_together': {('competition', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, default='', max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('external_source', models.CharField(blank=True, default='', max_length=50)),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='player_avatars/')),
            ],
            options={
                'indexes': [models.Index(fields=['external_source', 'external_id'], name='realdata_pl_externa_a8d114_idx'), models.Index(fields=['full_name'], name='realdata_pl_full_na_bc577c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, default='', max_length=40)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('external_source', models.CharField(blank=True, default='', max_length=50)),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['external_source', 'external_id'], name='realdata_te_externa_c1bdc5_idx'), models.Index(fields=['name'], name='realdata_te_name_b2ea3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='realdata.competitionseason')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='realdata.team')),
            ],
            options={
                'unique_together': {('competition_season', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.IntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField(blank=True, null=True)),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('external_source', models.CharField(blank=True, default='', max_length=50)),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='realdata.competitionseason')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='realdata.teamseason')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='realdata.teamseason')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('alias', models.CharField(max_length=120)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='realdata.player')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'alias'], name='realdata_pl_source_917d42_idx')],
                'unique_together': {('player', 'source', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='PlayerTeamStint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('transfer_kind', models.CharField(blank=True, default='', max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stints', to='realdata.player')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stints', to='realdata.teamseason')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'team_season'], name='realdata_pl_player__756b55_idx'), models.Index(fields=['team_season', 'start_date'], name='realdata_pl_team_se_370e1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('minutes_played', models.IntegerField(default=0)),
                ('is_starter', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='realdata.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='realdata.player')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appearances', to='realdata.teamseason')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'side'], name='realdata_ma_match_i_58b967_idx'), models.Index(fields=['match', 'team_season'], name='realdata_ma_match_i_0ceaff_idx')],
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['competition_season', 'matchday'], name='realdata_ma_competi_e18f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['external_source', 'external_id'], name='realdata_ma_externa_ce162b_idx'),
        ),
    ]
