# Generated by Django 5.2.10 on 2026-02-14 23:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerZoneFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('zone_key', models.CharField(max_length=24)),
                ('feature_key', models.CharField(max_length=64)),
                ('value', models.FloatField(default=0.0)),
                ('provider', models.CharField(choices=[('statsbomb', 'StatsBomb'), ('wyscout', 'Wyscout'), ('sofascore', 'SofaScore')], default='statsbomb', max_length=24)),
                ('source_method', models.CharField(default='event_spatial_exact', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_zone_features', to='realdata.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_features', to='realdata.player')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'player'], name='realdata_pl_match_i_4ade8e_idx'), models.Index(fields=['match', 'zone_key'], name='realdata_pl_match_i_c55941_idx'), models.Index(fields=['feature_key'], name='realdata_pl_feature_b43d49_idx')],
                'unique_together': {('match', 'player', 'team_side', 'zone_key', 'feature_key', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='RawMatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('statsbomb', 'StatsBomb'), ('wyscout', 'Wyscout'), ('sofascore', 'SofaScore')], default='statsbomb', max_length=24)),
                ('provider_event_id', models.CharField(max_length=64)),
                ('event_index', models.IntegerField(default=0)),
                ('period', models.IntegerField(default=1)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('event_family', models.CharField(max_length=40)),
                ('event_type', models.CharField(blank=True, default='', max_length=80)),
                ('event_subtype', models.CharField(blank=True, default='', max_length=80)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('x_end', models.FloatField(blank=True, null=True)),
                ('y_end', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='realdata.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_events', to='realdata.player')),
                ('team_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_events', to='realdata.teamseason')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'event_index'], name='realdata_ra_match_i_16e989_idx'), models.Index(fields=['match', 'event_family'], name='realdata_ra_match_i_2e3cf0_idx'), models.Index(fields=['provider', 'event_type'], name='realdata_ra_provide_ecff01_idx'), models.Index(fields=['team_side', 'minute'], name='realdata_ra_team_si_abb255_idx')],
                'unique_together': {('match', 'provider', 'provider_event_id')},
            },
        ),
        migrations.CreateModel(
            name='TeamZoneFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('zone_key', models.CharField(max_length=24)),
                ('feature_key', models.CharField(max_length=64)),
                ('value', models.FloatField(default=0.0)),
                ('provider', models.CharField(choices=[('statsbomb', 'StatsBomb'), ('wyscout', 'Wyscout'), ('sofascore', 'SofaScore')], default='statsbomb', max_length=24)),
                ('source_method', models.CharField(default='event_spatial_exact', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_zone_features', to='realdata.match')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'team_side'], name='realdata_te_match_i_1cd6c8_idx'), models.Index(fields=['match', 'zone_key'], name='realdata_te_match_i_a04103_idx'), models.Index(fields=['feature_key'], name='realdata_te_feature_db9c9a_idx')],
                'unique_together': {('match', 'team_side', 'zone_key', 'feature_key', 'provider')},
            },
        ),
    ]
