# Generated by Django 5.2.10 on 2026-02-15 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0002_playerzonefeature_rawmatchevent_teamzonefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('statsbomb', 'StatsBomb'), ('wyscout', 'Wyscout'), ('sofascore', 'SofaScore')], default='statsbomb', max_length=24)),
                ('dataset_key', models.CharField(default='default', max_length=80)),
                ('data_version', models.CharField(default='unknown', max_length=80)),
                ('formula_version', models.CharField(default='features_v1', max_length=80)),
                ('source_path', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'data_version'], name='realdata_da_provide_5f9eff_idx'), models.Index(fields=['imported_at'], name='realdata_da_importe_f7f441_idx')],
                'unique_together': {('provider', 'dataset_key', 'data_version', 'formula_version')},
            },
        ),
        migrations.DeleteModel(
            name='RawMatchEvent',
        ),
    ]
