# Generated by Django 5.2.10 on 2026-06-07 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0003_dataingestionmanifest_delete_rawmatchevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDisciplinaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('period', models.IntegerField(default=1)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('elapsed_seconds', models.IntegerField(default=0)),
                ('card_type', models.CharField(choices=[('yellow', 'Yellow'), ('second_yellow', 'Second Yellow'), ('red', 'Red'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('reason', models.CharField(blank=True, default='', max_length=80)),
                ('provider', models.CharField(choices=[('statsbomb', 'StatsBomb'), ('wyscout', 'Wyscout'), ('sofascore', 'SofaScore')], default='statsbomb', max_length=24)),
                ('provider_event_id', models.CharField(blank=True, default='', max_length=80)),
                ('source_event_type', models.CharField(blank=True, default='', max_length=80)),
                ('source_card_name', models.CharField(blank=True, default='', max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_events', to='realdata.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_events', to='realdata.player')),
                ('team_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_events', to='realdata.teamseason')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'team_side'], name='realdata_ma_match_i_077445_idx'), models.Index(fields=['match', 'player'], name='realdata_ma_match_i_21d1b3_idx'), models.Index(fields=['match', 'card_type'], name='realdata_ma_match_i_70fbf7_idx'), models.Index(fields=['provider', 'source_event_type'], name='realdata_ma_provide_12bf94_idx'), models.Index(fields=['minute', 'second'], name='realdata_ma_minute_19437c_idx')],
                'unique_together': {('match', 'provider', 'provider_event_id', 'card_type')},
            },
        ),
    ]
