# Generated by Django 5.2.10 on 2026-06-07 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0004_matchdisciplinaryevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerOnPitchInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('start_period', models.IntegerField(default=1)),
                ('start_minute', models.IntegerField(default=0)),
                ('start_second', models.IntegerField(default=0)),
                ('start_elapsed_seconds', models.IntegerField(default=0)),
                ('end_period', models.IntegerField(blank=True, null=True)),
                ('end_minute', models.IntegerField(default=90)),
                ('end_second', models.IntegerField(default=0)),
                ('end_elapsed_seconds', models.IntegerField(default=5400)),
                ('start_reason', models.CharField(choices=[('starting_xi', 'Starting XI'), ('substitution_on', 'Substitution On'), ('tactical_shift', 'Tactical Shift'), ('player_on', 'Player On'), ('unknown_start', 'Unknown Start')], default='unknown_start', max_length=32)),
                ('end_reason', models.CharField(choices=[('final_whistle', 'Final Whistle'), ('substitution_off', 'Substitution Off'), ('tactical_shift', 'Tactical Shift'), ('red_card', 'Red Card'), ('player_off', 'Player Off'), ('unknown_end', 'Unknown End')], default='unknown_end', max_length=32)),
                ('source_start_reason', models.CharField(blank=True, default='', max_length=120)),
                ('source_end_reason', models.CharField(blank=True, default='', max_length=120)),
                ('source_position', models.CharField(blank=True, default='', max_length=80)),
                ('provider', models.CharField(choices=[('statsbomb', 'StatsBomb'), ('wyscout', 'Wyscout'), ('sofascore', 'SofaScore')], default='statsbomb', max_length=24)),
                ('provider_interval_id', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_pitch_intervals', to='realdata.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_pitch_intervals', to='realdata.player')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='on_pitch_intervals', to='realdata.teamseason')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'team_side'], name='realdata_pl_match_i_920e97_idx'), models.Index(fields=['match', 'player'], name='realdata_pl_match_i_1259a2_idx'), models.Index(fields=['match', 'start_elapsed_seconds'], name='realdata_pl_match_i_fad99a_idx'), models.Index(fields=['match', 'end_elapsed_seconds'], name='realdata_pl_match_i_2306d8_idx'), models.Index(fields=['start_reason', 'end_reason'], name='realdata_pl_start_r_548a9b_idx')],
                'unique_together': {('match', 'player', 'provider', 'provider_interval_id')},
            },
        ),
    ]
