# Generated by Django 5.2.10 on 2026-06-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0005_playeronpitchinterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='data_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='data_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16),
        ),
        migrations.AddField(
            model_name='player',
            name='is_goalkeeper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'data_ready'], name='realdata_ma_status_919407_idx'),
        ),
    ]
