# Generated by Django 5.2.10 on 2026-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0006_match_data_checked_at_match_data_ready_match_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='classic_role',
            field=models.CharField(blank=True, choices=[('POR', 'Portiere'), ('DIF', 'Difensore'), ('CEN', 'Centrocampista'), ('ATT', 'Attaccante')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='role_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
