# Generated by Django 5.2.10 on 2026-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0007_player_classic_role_player_role_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchappearance',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchappearance',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
