# Generated by Django 5.2.10 on 2026-07-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0008_matchappearance_assists_matchappearance_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionseason',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='competitionseason',
            name='external_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='kickoff_provisional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='competitionseason',
            index=models.Index(fields=['external_source', 'external_id'], name='realdata_co_externa_5ee3c2_idx'),
        ),
    ]
