# Generated by Django 5.2.10 on 2026-07-21 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0010_match_finished_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMarketValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('provider_player_id', models.CharField(blank=True, default='', max_length=100)),
                ('value_eur', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('raw_value', models.CharField(blank=True, default='', max_length=32)),
                ('as_of', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_values', to='realdata.player')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'as_of'], name='realdata_pl_provide_b758f3_idx'), models.Index(fields=['player', 'provider'], name='realdata_pl_player__1f9bbb_idx')],
                'unique_together': {('player', 'provider', 'as_of')},
            },
        ),
    ]
