# Generated by Django 5.2.10 on 2026-07-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0011_playermarketvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteamstint',
            name='tm_position',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
