# Generated by Django 5.2.10 on 2026-07-22 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0012_playerteamstint_tm_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('zone_key', models.CharField(max_length=24)),
                ('xg', models.FloatField(default=0.0)),
                ('xgot', models.FloatField(default=0.0)),
                ('is_goal', models.BooleanField(default=False)),
                ('shot_type', models.CharField(blank=True, default='', max_length=24)),
                ('provider', models.CharField(choices=[('statsbomb', 'StatsBomb'), ('wyscout', 'Wyscout'), ('sofascore', 'SofaScore')], default='sofascore', max_length=24)),
                ('external_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='realdata.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='realdata.player')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'team_side'], name='realdata_ma_match_i_8f7f18_idx'), models.Index(fields=['match', 'minute'], name='realdata_ma_match_i_aba720_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('match', 'provider', 'external_id'), name='uniq_shot_per_provider_id')],
            },
        ),
    ]
