# Generated by Django 5.2.10 on 2026-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0013_match_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchappearance',
            name='raw_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
