# Generated by Django 5.2.10 on 2026-07-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0014_appearance_raw_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='classic_role',
            field=models.CharField(blank=True, choices=[('POR', 'Portiere'), ('DIF', 'Difensore'), ('CEN', 'Centrocampista'), ('ATT', 'Attaccante')], default='', help_text='Raw Transfermarkt provider seed (winger→CEN by convention), NOT the resolved scoring role — see SeasonPlayerRole / season_role_map().', max_length=3),
        ),
    ]
