# Generated by Django 5.2.10 on 2026-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0017_alter_player_classic_role_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchshot',
            name='elapsed_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
