# Generated by Django 5.2.10 on 2026-07-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0018_matchshot_elapsed_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchshot',
            name='situation',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
