# Generated by Django 5.2.10 on 2026-08-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0019_matchshot_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='data_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
