# Generated by Django 5.2.10 on 2026-08-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0020_match_data_imported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionseason',
            name='calendar_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
