# Generated by Django 5.2.10 on 2026-08-10 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0021_competitionseason_calendar_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(help_text='tick, sync_calendar, ...', max_length=40)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('due', models.JSONField(blank=True, default=dict)),
                ('did', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['job', '-started_at'], name='realdata_jo_job_fcffa1_idx'), models.Index(fields=['-started_at'], name='realdata_jo_started_9d0ae8_idx')],
            },
        ),
    ]
