# Generated by Django 5.2.10 on 2026-08-10 23:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0022_jobrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trigger', models.CharField(choices=[('alarm', 'Verdetto rosso'), ('weekly', 'Passata settimanale'), ('manual', 'A mano')], default='alarm', max_length=12)),
                ('agent_cmd', models.CharField(blank=True, default='', max_length=200)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('ok', models.BooleanField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['-started_at'], name='realdata_ma_started_5cb2c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('restart_unit', "Riavvia un'unita'"), ('rerun_command', 'Rilancia un comando'), ('clear_cache_file', 'Cancella un file di cache'), ('apply_patch', 'Applica una patch'), ('none', 'Nessuna azione')], max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'In attesa di un sì'), ('approved', 'Approvata, da eseguire'), ('rejected', 'Rifiutata'), ('done', 'Eseguita'), ('failed', 'Esecuzione fallita'), ('refused', 'Respinta dalla validazione')], default='proposed', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_decisions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='realdata.maintenancerun')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='realdata_ma_status_592517_idx'), models.Index(fields=['fingerprint'], name='realdata_ma_fingerp_4f9e74_idx')],
            },
        ),
    ]
