# Generated by Django 5.2.10 on 2026-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0024_spell_out_surname_particles'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='short_name_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
