# Generated by Django 5.2.10 on 2026-08-28 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0025_player_short_name_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('vfoot', 'Motore vfoot'), ('sofascore', 'SofaScore')], max_length=16)),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('home_formation', models.CharField(blank=True, default='', max_length=16)),
                ('away_formation', models.CharField(blank=True, default='', max_length=16)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_forecasts', to='realdata.match')),
            ],
        ),
        migrations.CreateModel(
            name='LineupForecastEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.IntegerField(default=0)),
                ('previous_probability', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('starter', 'Titolare'), ('bench', 'Panchina'), ('doubt', 'Ballottaggio'), ('out', 'Indisponibile')], default='bench', max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='realdata.lineupforecast')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_forecast_entries', to='realdata.player')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_forecast_entries', to='realdata.teamseason')),
            ],
        ),
        migrations.CreateModel(
            name='LineupEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.IntegerField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('injury', 'Infortunio'), ('suspension', 'Squalifica'), ('transfer', 'Mercato'), ('international', 'Nazionale'), ('internal', 'Fuori squadra'), ('note', 'Nota')], default='note', max_length=16)),
                ('availability', models.CharField(choices=[('out', 'Out'), ('doubt', 'In dubbio'), ('boost', 'Dato in campo')], default='doubt', max_length=8)),
                ('log_odds', models.FloatField(default=0.0)),
                ('source', models.CharField(default='admin', max_length=24)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_evidence', to='realdata.competitionseason')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_evidence', to='realdata.player')),
            ],
            options={
                'indexes': [models.Index(fields=['competition_season', 'matchday'], name='realdata_li_competi_cf8e5b_idx'), models.Index(fields=['player', 'matchday'], name='realdata_li_player__5ac316_idx'), models.Index(fields=['source'], name='realdata_li_source_0c3102_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lineupforecast',
            index=models.Index(fields=['match', 'source'], name='realdata_li_match_i_7e7627_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lineupforecast',
            unique_together={('match', 'source')},
        ),
        migrations.AddIndex(
            model_name='lineupforecastentry',
            index=models.Index(fields=['forecast', 'team_season'], name='realdata_li_forecas_406ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='lineupforecastentry',
            index=models.Index(fields=['player'], name='realdata_li_player__048958_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lineupforecastentry',
            unique_together={('forecast', 'player')},
        ),
    ]
