# Generated by Django 5.2.10 on 2026-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0026_lineupforecast_lineupforecastentry_lineupevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupforecast',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
