# Generated by Django 5.2.10 on 2026-08-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0027_lineupforecast_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineupforecast',
            name='source',
            field=models.CharField(choices=[('vfoot', 'Motore vfoot'), ('sofascore', 'SofaScore'), ('merged', 'Numero mostrato')], max_length=16),
        ),
    ]
