# Generated by Django 5.2.10 on 2026-08-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realdata', '0028_alter_lineupforecast_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchshot',
            name='assist_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_shots', to='realdata.player'),
        ),
    ]
